### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by siffiejoe** [saucisson/lua-coronest#2]
`import` in the readme should be `require`.

You should also consider uploading a source rock to the moonrocks site, so that users without `git` in the `PATH` (i.e. most Windows users) can install this module. You create a source rock by executing `luarocks pack coroutine-0.1-1.rockspec` (with the rockspec in the CWD). You can upload it on the moonrocks page for version 0.1-1 of the coroutine rock (using the owner tools). I also think that "coroutine" is too general for a rock name, but what's done is done.

**Comment by saucisson** [comment]
`require` is fixed

**Comment by saucisson** [comment]
Module has been renamed `coronest` (for coroutines that allow nesting), and project has been renamed also: https://github.com/saucisson/lua-coronest.

**Comment by saucisson** [comment]
Module has been uploaded to the rocks repository (rockspec and src).
